const donutsArray = [
  {
    id: 1,
    name: 'Chokladmunk med vaniljfyllning',
    price: 23,
    categories: ['glazed', 'filled'],
    images: ['img/chocolate-iced-cake.webp', 'img/chocolate-iced-custard-filled.webp'],
    rating: 5,
    discount: false,
  },
  {
    id: 2,
    name: 'Chokladmunk',
    price: 18,
    categories: ['glazed'],
    images: ['img/chocolate-iced-glazed.webp', 'img/chocolate-iced-glazed-cruller.webp'],
    rating: 4.5,
    discount: false,
  },
  {
    id: 3,
    name: 'Frostig drömmunk',
    price: 25,
    categories: ['glazed', 'filled'],
    images: ['img/glazed-blueberry-cake.webp', 'img/glazed-chocolate-cake.webp'],
    rating: 4.5,
    discount: false,
  },
  {
    id: 4,
    name: 'Strösslad kanelmunk',
    price: 13,
    categories: ['sprinkles'],
    images: ['img/glazed-cinnamon.webp', 'img/glazed-cruller.webp'],
    rating: 5,
    discount: false,
  },
  {
    id: 5,
    name: 'Snaskköping Special',
    price: 23,
    categories: ['glazed', 'filled'],
    images: ['img/double-dark-chocolate.webp', 'img/oreo-cookies-and-kreme.webp'],
    rating: 4,
    discount: false,
  },
  {
    id: 6,
    name: 'Jordgubbsmunk',
    price: 11,
    categories: ['glazed', 'sprinkles'],
    images: ['img/strawberry-iced.webp', 'img/strawberry-iced-with-sprinkles.webp'],
    rating: 5,
    discount: false,
  },
  {
    id: 7,
    name: 'Glaserad munk',
    price: 7,
    categories: ['glazed'],
    images: ['img/original-filled-chocolate-kreme.webp', 'img/original-filled-original-kreme.webp'],
    rating: 5,
    discount: false,
  },
  {
    id: 8,
    name: 'Gottfrids Favorit',
    price: 25,
    categories: ['sprinkles', 'filled'],
    images: ['img/new-york-cheesecake.webp', 'img/reese-s-classic.webp'],
    rating: 4.5,
    discount: false,
  },
  {
    id: 9,
    name: 'Pudrad munk med jordgubbsfyllning',
    price: 15,
    categories: ['filled'],
    images: ['img/powdered-cake.webp', 'img/powdered-strawberry-filled.webp'],
    rating: 4,
    discount: false,
  },
  {
    id: 10,
    name: 'Pudrad munk med blåbärsfyllning',
    price: 15,
    categories: ['filled'],
    images: ['img/powdered-cake.webp', 'img/powdered-blueberry-filled.webp'],
    rating: 4.5,
    discount: false,
  },
  {
    id: 11,
    name: 'Polisens Favorit',
    price: 9,
    categories: ['glazed', 'sprinkles'],
    images: ['img/chocolate-iced-glazed-with-sprinkles.webp', 'img/original-glazed-doughnut.webp'],
    rating: 4,
    discount: false,
  },
  {
    id: 12,
    name: 'Krämig munk',
    price: 16,
    categories: ['glazed', 'filled'],
    images: ['img/chocolate-iced-raspberry-filled.webp', 'img/chocolate-iced-with-kreme-filling.webp'],
    rating: 5,
    discount: false,
  },

];

export default donutsArray;
