/* eslint-disable max-len */
const donutsArray = [
  {
    id: 1,
    name: 'Chokladmunk med vaniljfyllning',
    price: 23,
    categories: ['glazed', 'filled'],
    images: ['img/chocolate-iced-cake.webp', 'img/chocolate-iced-custard-filled.webp'],
    alt: ['Chokladdoppad munk med hål och stjärnformad mitten.', 'Undersida utan hål av chokladdoppad munk.'],
    rating: 5,
    discount: false,
  },
  {
    id: 2,
    name: 'Chokladmunk',
    price: 18,
    categories: ['glazed'],
    images: ['img/chocolate-iced-glazed.webp', 'img/chocolate-iced-glazed-cruller.webp'],
    alt: ['Chokladdoppad munk med hål.', 'Undersida med räfflad yta av chokladdoppad munk.'],
    rating: 4.5,
    discount: false,
  },
  {
    id: 3,
    name: 'Frostig drömmunk',
    price: 25,
    categories: ['glazed', 'filled'],
    images: ['img/glazed-blueberry-cake.webp', 'img/glazed-chocolate-cake.webp'],
    alt: ['Rund, ljus munk med hål och glasyr.', 'Undersida av munk med hål och glasyr som är mörk.'],
    rating: 4.5,
    discount: false,
  },
  {
    id: 4,
    name: 'Strösslad kanelmunk',
    price: 13,
    categories: ['sprinkles'],
    images: ['img/glazed-cinnamon.webp', 'img/glazed-cruller.webp'],
    alt: ['Munk med hål som är strösslad med socker.', 'Undersida av munk som har räfflad yta glasyr.'],
    rating: 5,
    discount: false,
  },
  {
    id: 5,
    name: 'Snaskköping Special',
    price: 23,
    categories: ['glazed', 'filled'],
    images: ['img/double-dark-chocolate.webp', 'img/oreo-cookies-and-kreme.webp'],
    alt: ['Chokladdoppad munk utan hål som är dekorerad med mer choklad i ränder.', 'Undersida med oreo-strössel och som är dekorerad med vit choklad.'],
    rating: 4,
    discount: false,
  },
  {
    id: 6,
    name: 'Jordgubbsmunk',
    price: 11,
    categories: ['glazed', 'sprinkles'],
    images: ['img/strawberry-iced.webp', 'img/strawberry-iced-with-sprinkles.webp'],
    alt: ['Rund munk med hål och rosa glasyr.', 'Andra sidan av en munk med rosa glasyr och strössel.'],
    rating: 5,
    discount: false,
  },
  {
    id: 7,
    name: 'Glaserad munk',
    price: 7,
    categories: ['glazed'],
    images: ['img/original-filled-chocolate-kreme.webp', 'img/original-filled-original-kreme.webp'],
    alt: ['Rund munk med hål och glasyr samt dekorerad med chokladränder.', 'Rund munk med hål och glasyr samt dekorerad med vita chokladränder.'],
    rating: 5,
    discount: false,
  },
  {
    id: 8,
    name: 'Gottfrids Favorit',
    price: 25,
    categories: ['sprinkles', 'filled'],
    images: ['img/new-york-cheesecake.webp', 'img/reese-s-classic.webp'],
    alt: ['Mandelströsslad munk med vit mjukost.', 'Undersida av munk med choklad och mandel- och chokladströssel dekorerad med chokladstreck.'],
    rating: 4.5,
    discount: false,
  },
  {
    id: 9,
    name: 'Pudrad munk med jordgubbsfyllning',
    price: 15,
    categories: ['filled'],
    images: ['img/powdered-cake.webp', 'img/powdered-strawberry-filled.webp'],
    alt: ['Pudrad munk med stjärnformat hål.', 'Undersida av pudrad munk utan hål dekorerad med jordgubbssylt.'],
    rating: 4,
    discount: false,
  },
  {
    id: 10,
    name: 'Pudrad munk med blåbärsfyllning',
    price: 15,
    categories: ['filled'],
    images: ['img/powdered-cake.webp', 'img/powdered-blueberry-filled.webp'],
    alt: ['Pudrad munk med stjärnformat hål.', 'Undersida av pudrad munk utan hål dekorerad med blåbärssylt.'],
    rating: 4.5,
    discount: false,
  },
  {
    id: 11,
    name: 'Polisens Favorit',
    price: 9,
    categories: ['glazed', 'sprinkles'],
    images: ['img/chocolate-iced-glazed-with-sprinkles.webp', 'img/original-glazed-doughnut.webp'],
    alt: ['Chokladdoppad munk med hål och strössel.', 'Undersida av munk med glasyr.'],
    rating: 4,
    discount: false,
  },
  {
    id: 12,
    name: 'Krämig munk',
    price: 16,
    categories: ['glazed', 'filled'],
    images: ['img/chocolate-iced-raspberry-filled.webp', 'img/chocolate-iced-with-kreme-filling.webp'],
    alt: ['Rund chokladdoppad munk med röda dekorationer', 'Undersida av munk som är chokladdoppad.'],
    rating: 5,
    discount: false,
  },

];

export default donutsArray;
