const donutsArray = [
  {
    id: 1,
    name: 'Chokladmunk med vaniljfyllning',
    price: 23,
    categories: ['glazed', 'filled'],
    images: ['img/chocolate-iced-custard-filled.jpeg', 'img/cinnamon-apple-filled.jpeg'],
    rating: 5,
    discount: false,
  },
  {
    id: 2,
    name: 'Chokladmunk',
    price: 18,
    categories: ['glazed'],
    images: ['img/chocolate-iced-glazed.jpeg', 'img/chocolate-iced-custard-filled.jpeg'],
    rating: 4.5,
    discount: false,
  },
  {
    id: 3,
    name: 'Kanelpudrad munk med äppelfyllning',
    price: 25,
    categories: ['filled', 'sprinkles'],
    images: ['img/cinnamon-apple-filled.jpeg', 'img/chocolate-iced-custard-filled.jpeg'],
    rating: 4.5,
    discount: false,
  },
  {
    id: 4,
    name: 'Glaserad kanelmunk',
    price: 13,
    categories: ['glazed', 'sprinkles'],
    images: ['img/glazed-cinnamon.jpeg', 'img/chocolate-iced-custard-filled.jpeg'],
    rating: 5,
    discount: false,
  },
  {
    id: 5,
    name: 'Glaserad munk med citronfyllning',
    price: 23,
    categories: ['glazed', 'filled'],
    images: ['img/glazed-lemon-filled.jpeg', 'img/chocolate-iced-custard-filled.jpeg'],
    rating: 4,
    discount: false,
  },
  {
    id: 6,
    name: 'Munk med chokladfyllning',
    price: 16,
    categories: ['filled'],
    images: ['img/original-filled-chocolate-kreme™.jpeg', 'img/chocolate-iced-custard-filled.jpeg'],
    rating: 4,
    discount: false,
  },
  {
    id: 7,
    name: 'Glaserad munk',
    price: 7,
    categories: ['glazed'],
    images: ['img/original-glazed-doughnut.jpeg', 'img/chocolate-iced-custard-filled.jpeg'],
    rating: 5,
    discount: false,
  },
  {
    id: 8,
    name: 'Pudrad munk med blåbärsfyllning',
    price: 25,
    categories: ['sprinkles', 'filled'],
    images: ['img/powdered-blueberry-filled.jpeg', 'img/chocolate-iced-custard-filled.jpeg'],
    rating: 4.5,
    discount: false,
  },
  {
    id: 9,
    name: 'Pudrad munk med jordgubbsfyllning',
    price: 25,
    categories: ['sprinkles', 'filled'],
    images: ['img/powdered-strawberry-filled.jpeg', 'img/chocolate-iced-custard-filled.jpeg'],
    rating: 4,
    discount: false,
  },
  {
    id: 10,
    name: 'Jordgubbsmunk',
    price: 11,
    categories: ['glazed'],
    images: ['img/strawberry-iced.jpeg', 'img/chocolate-iced-custard-filled.jpeg'],
    rating: 5,
    discount: false,
  },
];

export default donutsArray;
